//
// This file was generated by the Jeddict
//
package pl.edu.prz.kia.universityproject.model.domain;

import java.io.Serializable;
import java.util.Objects;

public class KIERUNEKPK implements Serializable {

    private Integer ID_kierunku;

    private Integer WYDZIAL;

    public KIERUNEKPK() {
    }

    public KIERUNEKPK(Integer ID_kierunku, Integer WYDZIAL) {
        this.ID_kierunku = ID_kierunku;
        this.WYDZIAL = WYDZIAL;
    }

    public Integer getID_kierunku() {
        return this.ID_kierunku;
    }

    public void setID_kierunku(Integer ID_kierunku) {
        this.ID_kierunku = ID_kierunku;
    }

    public Integer getWYDZIAL() {
        return this.WYDZIAL;
    }

    public void setWYDZIAL(Integer WYDZIAL) {
        this.WYDZIAL = WYDZIAL;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!Objects.equals(getClass(), obj.getClass())) {
            return false;
        }
        final KIERUNEKPK other = (KIERUNEKPK) obj;
        if (!java.util.Objects.equals(this.getID_kierunku(), other.getID_kierunku())) {
            return false;
        }
        if (!java.util.Objects.equals(this.getWYDZIAL(), other.getWYDZIAL())) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 31 * hash + Objects.hashCode(this.getID_kierunku());
        hash = 31 * hash + Objects.hashCode(this.getWYDZIAL());
        return hash;
    }

    @Override
    public String toString() {
        return "KIERUNEKPK{" + " ID_kierunku=" + ID_kierunku + ", WYDZIAL=" + WYDZIAL + '}';
    }

}