/**
 * This file was generated by the Jeddict
 */
package pl.edu.prz.kia.universityproject.model.domain;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.validation.constraints.NotNull;

/**
 * @author Krystian
 */
@Entity
@IdClass(KIERUNEKPK.class)
public class KIERUNEK {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @NotNull
    private Integer ID_kierunku;

    @Basic
    @NotNull
    private String Nazwa;

    @Basic
    private String Opis;

    @Id
    @ManyToOne
    private WYDZIAL WYDZIAL;

    @ManyToMany
    private List<UZYTKOWNIK> UZYTKOWNIKs;

    public Integer getID_kierunku() {
        return this.ID_kierunku;
    }

    public void setID_kierunku(Integer ID_kierunku) {
        this.ID_kierunku = ID_kierunku;
    }

    public String getNazwa() {
        return this.Nazwa;
    }

    public void setNazwa(String Nazwa) {
        this.Nazwa = Nazwa;
    }

    public String getOpis() {
        return this.Opis;
    }

    public void setOpis(String Opis) {
        this.Opis = Opis;
    }

    public WYDZIAL getWYDZIAL() {
        return this.WYDZIAL;
    }

    public void setWYDZIAL(WYDZIAL WYDZIAL) {
        this.WYDZIAL = WYDZIAL;
    }

    public List<UZYTKOWNIK> getUZYTKOWNIKs() {
        if (UZYTKOWNIKs == null) {
            UZYTKOWNIKs = new ArrayList<>();
        }
        return this.UZYTKOWNIKs;
    }

    public void setUZYTKOWNIKs(List<UZYTKOWNIK> UZYTKOWNIKs) {
        this.UZYTKOWNIKs = UZYTKOWNIKs;
    }

    public void addUZYTKOWNIK(UZYTKOWNIK UZYTKOWNIK) {
        getUZYTKOWNIKs().add(UZYTKOWNIK);
        UZYTKOWNIK.getKIERUNEKs().add(this);
    }

    public void removeUZYTKOWNIK(UZYTKOWNIK UZYTKOWNIK) {
        getUZYTKOWNIKs().remove(UZYTKOWNIK);
        UZYTKOWNIK.getKIERUNEKs().remove(this);
    }

}