/**
 * This file was generated by the Jeddict
 */
package pl.edu.prz.kia.universityproject.model.domain;

import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.validation.constraints.NotNull;

/**
 * @author Krystian
 */
@Entity
@IdClass(ODPOWIEDZ_UZYTKOWNIKAPK.class)
public class ODPOWIEDZ_UZYTKOWNIKA {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @NotNull
    private Integer ID_odpowiedzi;

    @Basic
    private Integer Wartosc;

    @Id
    @ManyToOne
    private UZYTKOWNIK UZYTKOWNIK;

    @Id
    @ManyToOne
    private PYTANIE PYTANIE;

    public Integer getID_odpowiedzi() {
        return this.ID_odpowiedzi;
    }

    public void setID_odpowiedzi(Integer ID_odpowiedzi) {
        this.ID_odpowiedzi = ID_odpowiedzi;
    }

    public Integer getWartosc() {
        return this.Wartosc;
    }

    public void setWartosc(Integer Wartosc) {
        this.Wartosc = Wartosc;
    }

    public UZYTKOWNIK getUZYTKOWNIK() {
        return this.UZYTKOWNIK;
    }

    public void setUZYTKOWNIK(UZYTKOWNIK UZYTKOWNIK) {
        this.UZYTKOWNIK = UZYTKOWNIK;
    }

    public PYTANIE getPYTANIE() {
        return this.PYTANIE;
    }

    public void setPYTANIE(PYTANIE PYTANIE) {
        this.PYTANIE = PYTANIE;
    }

}