//
// This file was generated by the Jeddict
//
package pl.edu.prz.kia.universityproject.model.domain;

import java.io.Serializable;
import java.util.Objects;

public class ODPOWIEDZ_UZYTKOWNIKAPK implements Serializable {

    private Integer ID_odpowiedzi;

    private Integer UZYTKOWNIK;

    private Integer PYTANIE;

    public ODPOWIEDZ_UZYTKOWNIKAPK() {
    }

    public ODPOWIEDZ_UZYTKOWNIKAPK(Integer ID_odpowiedzi, Integer UZYTKOWNIK, Integer PYTANIE) {
        this.ID_odpowiedzi = ID_odpowiedzi;
        this.UZYTKOWNIK = UZYTKOWNIK;
        this.PYTANIE = PYTANIE;
    }

    public Integer getID_odpowiedzi() {
        return this.ID_odpowiedzi;
    }

    public void setID_odpowiedzi(Integer ID_odpowiedzi) {
        this.ID_odpowiedzi = ID_odpowiedzi;
    }

    public Integer getUZYTKOWNIK() {
        return this.UZYTKOWNIK;
    }

    public void setUZYTKOWNIK(Integer UZYTKOWNIK) {
        this.UZYTKOWNIK = UZYTKOWNIK;
    }

    public Integer getPYTANIE() {
        return this.PYTANIE;
    }

    public void setPYTANIE(Integer PYTANIE) {
        this.PYTANIE = PYTANIE;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!Objects.equals(getClass(), obj.getClass())) {
            return false;
        }
        final ODPOWIEDZ_UZYTKOWNIKAPK other = (ODPOWIEDZ_UZYTKOWNIKAPK) obj;
        if (!java.util.Objects.equals(this.getID_odpowiedzi(), other.getID_odpowiedzi())) {
            return false;
        }
        if (!java.util.Objects.equals(this.getUZYTKOWNIK(), other.getUZYTKOWNIK())) {
            return false;
        }
        if (!java.util.Objects.equals(this.getPYTANIE(), other.getPYTANIE())) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 31 * hash + Objects.hashCode(this.getID_odpowiedzi());
        hash = 31 * hash + Objects.hashCode(this.getUZYTKOWNIK());
        hash = 31 * hash + Objects.hashCode(this.getPYTANIE());
        return hash;
    }

    @Override
    public String toString() {
        return "ODPOWIEDZ_UZYTKOWNIKAPK{" + " ID_odpowiedzi=" + ID_odpowiedzi + ", UZYTKOWNIK=" + UZYTKOWNIK + ", PYTANIE=" + PYTANIE + '}';
    }

}