/**
 * This file was generated by the Jeddict
 */
package pl.edu.prz.kia.universityproject.model.domain;

import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.validation.constraints.NotNull;

/**
 * @author Krystian
 */
@Entity
public class PYTANIE {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @NotNull
    private Integer ID_pytania;

    @Basic
    @NotNull
    private String Tresc;

    public Integer getID_pytania() {
        return this.ID_pytania;
    }

    public void setID_pytania(Integer ID_pytania) {
        this.ID_pytania = ID_pytania;
    }

    public String getTresc() {
        return this.Tresc;
    }

    public void setTresc(String Tresc) {
        this.Tresc = Tresc;
    }

}