/**
 * This file was generated by the Jeddict
 */
package pl.edu.prz.kia.universityproject.model.domain;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.validation.constraints.NotNull;

/**
 * @author Krystian
 */
@Entity
public class ROLA {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long ID_roli;

    @Basic
    @NotNull
    private String Nazwa;

    @ManyToMany
    private List<UZYTKOWNIK> UZYTKOWNIKs;

    public Long getID_roli() {
        return this.ID_roli;
    }

    public void setID_roli(Long ID_roli) {
        this.ID_roli = ID_roli;
    }

    public String getNazwa() {
        return this.Nazwa;
    }

    public void setNazwa(String Nazwa) {
        this.Nazwa = Nazwa;
    }

    public List<UZYTKOWNIK> getUZYTKOWNIKs() {
        if (UZYTKOWNIKs == null) {
            UZYTKOWNIKs = new ArrayList<>();
        }
        return this.UZYTKOWNIKs;
    }

    public void setUZYTKOWNIKs(List<UZYTKOWNIK> UZYTKOWNIKs) {
        this.UZYTKOWNIKs = UZYTKOWNIKs;
    }

    public void addUZYTKOWNIK(UZYTKOWNIK UZYTKOWNIK) {
        getUZYTKOWNIKs().add(UZYTKOWNIK);
    }

    public void removeUZYTKOWNIK(UZYTKOWNIK UZYTKOWNIK) {
        getUZYTKOWNIKs().remove(UZYTKOWNIK);
    }

}