/**
 * This file was generated by the Jeddict
 */
package pl.edu.prz.kia.universityproject.model.domain;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.validation.constraints.NotNull;

/**
 * @author Krystian
 */
@Entity
public class UZYTKOWNIK {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer ID_uzytkownika;

    @Basic
    @NotNull
    private String Imie;

    @Basic
    @NotNull
    private String Nazwisko;

    @Basic
    @NotNull
    private String Mail;

    @Basic
    @NotNull
    private String Haslo;

    @Basic
    @NotNull
    private String Ankieta;

    @Basic
    private String Awatar;

    @ManyToMany(mappedBy = "UZYTKOWNIKs")
    private List<KIERUNEK> KIERUNEKs;

    public Integer getID_uzytkownika() {
        return this.ID_uzytkownika;
    }

    public void setID_uzytkownika(Integer ID_uzytkownika) {
        this.ID_uzytkownika = ID_uzytkownika;
    }

    public String getImie() {
        return this.Imie;
    }

    public void setImie(String Imie) {
        this.Imie = Imie;
    }

    public String getNazwisko() {
        return this.Nazwisko;
    }

    public void setNazwisko(String Nazwisko) {
        this.Nazwisko = Nazwisko;
    }

    public String getMail() {
        return this.Mail;
    }

    public void setMail(String Mail) {
        this.Mail = Mail;
    }

    public String getHaslo() {
        return this.Haslo;
    }

    public void setHaslo(String Haslo) {
        this.Haslo = Haslo;
    }

    public String getAnkieta() {
        return this.Ankieta;
    }

    public void setAnkieta(String Ankieta) {
        this.Ankieta = Ankieta;
    }

    public String getAwatar() {
        return this.Awatar;
    }

    public void setAwatar(String Awatar) {
        this.Awatar = Awatar;
    }

    public List<KIERUNEK> getKIERUNEKs() {
        if (KIERUNEKs == null) {
            KIERUNEKs = new ArrayList<>();
        }
        return this.KIERUNEKs;
    }

    public void setKIERUNEKs(List<KIERUNEK> KIERUNEKs) {
        this.KIERUNEKs = KIERUNEKs;
    }

    public void addKIERUNEK(KIERUNEK KIERUNEK) {
        getKIERUNEKs().add(KIERUNEK);
    }

    public void removeKIERUNEK(KIERUNEK KIERUNEK) {
        getKIERUNEKs().remove(KIERUNEK);
    }

}