//
// This file was generated by the Jeddict
//
package pl.edu.prz.kia.universityproject.model.domain;

import java.io.Serializable;
import java.util.Objects;

public class WARTOSC_OCZEKIWANAPK implements Serializable {

    private Integer ID_wartosci;

    private KIERUNEKPK KIERUNEK;

    private Integer PYTANIE;

    public WARTOSC_OCZEKIWANAPK() {
    }

    public WARTOSC_OCZEKIWANAPK(Integer ID_wartosci, KIERUNEKPK KIERUNEK, Integer PYTANIE) {
        this.ID_wartosci = ID_wartosci;
        this.KIERUNEK = KIERUNEK;
        this.PYTANIE = PYTANIE;
    }

    public Integer getID_wartosci() {
        return this.ID_wartosci;
    }

    public void setID_wartosci(Integer ID_wartosci) {
        this.ID_wartosci = ID_wartosci;
    }

    public KIERUNEKPK getKIERUNEK() {
        return this.KIERUNEK;
    }

    public void setKIERUNEK(KIERUNEKPK KIERUNEK) {
        this.KIERUNEK = KIERUNEK;
    }

    public Integer getPYTANIE() {
        return this.PYTANIE;
    }

    public void setPYTANIE(Integer PYTANIE) {
        this.PYTANIE = PYTANIE;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (!Objects.equals(getClass(), obj.getClass())) {
            return false;
        }
        final WARTOSC_OCZEKIWANAPK other = (WARTOSC_OCZEKIWANAPK) obj;
        if (!java.util.Objects.equals(this.getID_wartosci(), other.getID_wartosci())) {
            return false;
        }
        if (!java.util.Objects.equals(this.getKIERUNEK(), other.getKIERUNEK())) {
            return false;
        }
        if (!java.util.Objects.equals(this.getPYTANIE(), other.getPYTANIE())) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 31 * hash + Objects.hashCode(this.getID_wartosci());
        hash = 31 * hash + Objects.hashCode(this.getKIERUNEK());
        hash = 31 * hash + Objects.hashCode(this.getPYTANIE());
        return hash;
    }

    @Override
    public String toString() {
        return "WARTOSC_OCZEKIWANAPK{" + " ID_wartosci=" + ID_wartosci + ", KIERUNEK=" + KIERUNEK + ", PYTANIE=" + PYTANIE + '}';
    }

}