/**
 * This file was generated by the Jeddict
 */
package pl.edu.prz.kia.universityproject.model.domain;

import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.validation.constraints.NotNull;

/**
 * @author Krystian
 */
@Entity
public class WYDZIAL {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @NotNull
    private Integer ID_wydzialu;

    @Basic
    @NotNull
    private String Nazwa;

    @Basic
    private String Logo;

    @Basic
    @NotNull
    private String Adres;

    public Integer getID_wydzialu() {
        return this.ID_wydzialu;
    }

    public void setID_wydzialu(Integer ID_wydzialu) {
        this.ID_wydzialu = ID_wydzialu;
    }

    public String getNazwa() {
        return this.Nazwa;
    }

    public void setNazwa(String Nazwa) {
        this.Nazwa = Nazwa;
    }

    public String getLogo() {
        return this.Logo;
    }

    public void setLogo(String Logo) {
        this.Logo = Logo;
    }

    public String getAdres() {
        return this.Adres;
    }

    public void setAdres(String Adres) {
        this.Adres = Adres;
    }

}